### ISSUE TITLE
Communications: CLIC and TIN Highlight Domain Teams

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/operations#128] opened 2020-09-23 17:35 UTC
- [ ] Highlight 1-2 Domain Teams on the CLIC and TIN websites each week 
- [ ] Can use the same text but also include the project DUR text that is APPROVED by the DAC
- [ ] List the benefits of joining this Domain team, opportunities
- [ ] List the roles needed...Statisticians, Clinicians, ML, nursing... for the domain teams . @andrewjneumann 
- [x] Place on the Communication agenda for next week with CLIC

- [x] CTSA leadership recommended changing the name of the "Emergency Department Avoidance"  Domain team to "Emergency Services" to be more inclusive of other ER researchers and clinicians.

**Comment by amvolz** [comment] 2020-09-23 22:34
- Has been placed on the Communications meeting agenda
- Domain name has been changed as above on the website. I will leave unchecked for Andrew to change the name in other places.

**Comment by amvolz** [comment] 2020-10-22 19:22
See [ticket #61 in the covid website repository.](https://github.com/National-COVID-Cohort-Collaborative/covid.cd2h.org/issues/61) It is a duplicate of this.

**Closed as completed** 2020-11-19 22:24 UTC
